### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by BIGEAZY289** [Matheus-0/LookMovie-DL#1]
Is there any android version for this app?

**Comment by Matheus-0** [comment]
No, there isn't.

**Comment by BIGEAZY289** [comment]
Are you going to make one?

**Comment by Matheus-0** [comment]
It's not in my plans, I don't have the time to make an app right now.

**Comment by BIGEAZY289** [comment]
Sed I was waiting for someone to build an app for this website it's great

**Comment by Matheus-0** [comment]
Indeed it is, I was excited to make this.
I'll be closing this issue now.
